### ISSUE TITLE
4 Leerzeichen statt 2 verwenden

### ISSUE THREAD

**Issue by NullEnt1ty** [5minds/javascript-guidelines#5]

**Comment by 5ebastianMeier** [comment]
Ich nehme an, dass das mit dem Ziel besserer Lesbarkeit vorgeschlagen wurde.

Mir leistet es dabei offen gestanden einen Bärendienst weil ich es als deutlich anstrengender empfinde eine breite Einrückung zu lesen.

Zudem beschränkt es uns zusätzlich in der Länge von Methodennamen, da die zusätzliche Einrückung weniger Platz für lange Methodennamen lässt (lange Methodennamen sind nicht zwingend ein schlechtes Stilmittel)

**Comment by moellenbeck** [comment]
@5ebastianMeier aber nur um 2 Zeichen und damit nicht so relevant. Der vereinheitlichte Stil ist aus meiner Sicht besser (.NET -> C#).

**Comment by cmg-dev** [comment]
Im Sinne der Einheitlichkeit, finde ich das auch sehr zu befürworten.

**Comment by LeoTT** [comment]
Wird behandelt durch PullRequest #6

**Comment by 5ebastianMeier** [comment]
@moellenbeck wir werden den Stil aber ohnehin nicht vollständig angleichen, bspw. dass in JavaScript und TypeScript die Body-Klammern in der Zeile der Methodensignatur stehen.

Ich nehme an, dass du Pull Requests dadurch leserlicher findest aber ich muss sagen, dass selbst dort mich 4 Leerzeichen gegenüber 2 Leerzeichen stören - der Code wird für mich dadurch nicht lesbarer, ganz im Gegenteil

In .NET/C# fällt sowas denke ich auch nicht so stark auf weil die Einrückungstiefe seltener durch eingeschobene Callbacks o.ä. forciert wird - in JavaScript und TypeScript hingegen haben wir häufig tiefere Einrückungshierarchien (selbst mit gutem Stil) als in .NET/C#.

Das bitte ich zu berücksichtigen.

**Comment by 5ebastianMeier** [comment]
Eine kleine Linksammlung - wir haben die Diskussion nicht erfunden ;)

http://docs.scala-lang.org/style/indentation.html
https://stackoverflow.com/questions/6741586/rails-coding-standards-why-2-space-indentation
https://github.com/avh4/elm-format/issues/158
https://github.com/avh4/elm-format/issues/80
https://developers.google.com/edu/python/introduction?csw=1#indentation

Da findet man sicher noch mehr. Mir geht es darum, dass .NET/C# nicht unser einziges Sorgenkind ist und imho auch nicht zwingend solche Konventionen vorgeben sollte.

**Comment by heikomat** [comment]
Hm... persönlich finde ich 2 spaces übersichtlicher als 4, Und zu sagen wir machen in JS jetzt 4 leerzeichen weil C# finde ich jetzt kein sehr überzeugendes Argument.
Ebenso gut könnte man sagen wir machen in C# 2 leerzeichen, weil JS.

Vergleichsweise machen wir soweit ich weiß in C# die `{` immer in eine neue Zeile, in JS immer in die gleiche Zeile.

Wir haben seit wir den JS-Styleguide aufgesetzt haben gesagt: 2 spaces. Warum jetzt umstellen?

**Comment by moellenbeck** [comment]
Wir stellen nicht einfach um, sondern es wurde einfach umgestellt, in der Haupt-Huf-Zeit waren es IMMER 4 Zeichen! Und daher würde ich mir wünschen dass es so bleibt und NICHT einfach (ohne mein Zutun) geändert wird!

**Comment by heikomat** [comment]
@moellenbeck ist nicht wahr, grade in dem ursprungs-styleguide von HUF geschaut, auf Seite 23 (bzw. 25) steht, dass 2 spaces verwendet werden sollen: https://drive.google.com/drive/folders/0BzM63DCQ4t0VOGUtOGMwWnlHMUk

**Comment by ElRaptorus** [comment]
Ich kann mich nicht erinnern bei Huf jemals mit 4 Spaces gearbeitet zu haben...

Ansonsten stimm ich @heikomat und @5ebastianMeier zu, ich finde 4 Spaces bei JS auch eher weniger lesbar.

**Comment by moellenbeck** [comment]
ok, dann muss ich zugestehen, dass ich mich da vertan haben und eine falsche Erinnerung abgespeichert habe (ich denke die bezieht sich eher auf: https://github.com/Microsoft/TypeScript/blob/master/src/compiler/core.ts)

sorry - dann wohl 2 Zeichen (ich würde nicht wollen, dass wir alles bisherige in Frage stellen, zuviel Code)
