### ISSUE TITLE
Plädoyer gegen null

### ISSUE THREAD

**Issue by LeoTT** [5minds/javascript-guidelines#8]
Ich möchte mich dafür aussprechen den Wert `null` wo möglich zu vermeiden und stattdessen nur `undefined` zu nutzen.

# Warum?
## zusätzliche Komplexität
Um Nichtwertigkeit zu kontrollieren muss man beides überprüfen (es sei denn wir können `null` ausschließen:
```javascript
if (a !== undefined && a !== null) { // boilerplate und kann durch Nachlässigkeit falsch gemacht werden
...

// Folgendes ist keine gute Alternative ...
if (!a) {
...
// ... denn a könnte auch z.B. false oder 0 sein und das will man gar nicht hier kontrollieren. Kann verwirrende Fehler geben.
```

## typeof null ist kaputt (ergibt 'object')
Im Folgenden würde ich ohne null-Paranoia davon ausgehen, dass die Kontrolle nach `a.id` sicher ist. Es kommt aber ein Fehler und die Firefox Fehlermeldung `TypeError: null has no properties` könnte mich richtig irritieren bei der Zeile.
```javascript
var a = null;
...
if (typeof a === 'object' && a.id) {
...
```
## kein semantischer Gewinn (persönliche Meinung)
`undefined` drückt einen nicht initialisierten Wert aus, `null` drückt einen Wert aus, welchen man gezielt setzt. 
Klingt sinnvoll, aber es gelingt mir nicht ein Beispiel zu konstruieren, wo das notwendig ist und wenn es das wäre ließe es sich ebenso elegant durch eine weitere boolean variable unterscheiden.

# Zusatzinformationen
- Microsoft TypeScript [Styleguide](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines) (nicht für die Sprache, sondern der Entwicklung am Compiler) beinhaltet den Verzicht von `null`.
- TypeScript hat non-nullable Types (müssen per Flag aktiviert werden). Damit kann man sicherstellen, dass null vermieden wird. null gezielt zu erlauben ist einfach und intuitiv (let a: string | null)
- Douglas Crockford [argumentiert gegen null](https://youtu.be/NPB34lDZj3E?t=12m29s)
- null kommt selten im JS-Ökosystem vor. Ich kenns in erster Linie aus DOM-Operationen.
```javascript
document.body.getAttribute('gimli') // => null
```
Dann muss man halt mit null prüfen. Lässt sich aber gut reduzieren auf die wenigen nötigen Fälle.
- JSON.stringify filtert Eigenschaften mit Wert `undefined` raus.
```javascript
JSON.stringify({
  a: null,
  b: undefined,
}); // => "{\"a\":null}"
```
Praktisch das einzige Problem, das ich sehe.

**Comment by lmoe** [comment]
Das JSON.stringify undefined "rausfiltert" finde ich vollkommen richtig. Schließlich ist der Wert ja auch nicht definiert. 

Ob man jetzt ein Objekt mit fehlendem Property serialisiert, oder das Property auf undefined setzt ist am Ende das selbe.

```javascript
typeof ({}).test
'undefined'
```

```javascript
typeof ({test: undefined}).test
'undefined'
```
